### ISSUE TITLE
install soloud.source failure

### ISSUE THREAD

**Issue by kidnewthe** [arc80/FlapHero#2]
The step "install soloud.source" I alway failure because “error: install failed (Error downloading 'http://sol.gfxile.net/soloud/soloud_20200207_lite.zip)”，but I can download the file by myself.

**Comment by preshing** [comment]
PlyTool currently uses CMake to complete the download.

The next time PlyTool gives you this error, see what happens when you download the file using CMake. Create a file named `try_download.cmake`:

```
file(DOWNLOAD "http://sol.gfxile.net/soloud/soloud_20200207_lite.zip" "${CMAKE_CURRENT_LIST_DIR}/soloud_20200207_lite.zip" STATUS statusVar)
message("${statusVar}")
```

Then run:

```
> cmake -P try_download.cmake
```

...followed by (assuming you're on Windows):

```
> echo %ERRORLEVEL%
```

Then post the result of both commands here.

Alternatively, you could also open the PlyTool solution (`WORKSPACE_ROOT\data\build\bootstrap\plytool\build\plytool.sln`), put a breakpoint in `ply::build::downloadFile`) and launch PlyTool in the debugger with arguments `extern install soloud.source`.
