### ISSUE TITLE
Infinite recursion when running on Windows

### ISSUE THREAD

**Issue by jlaumon** [arc80/FlapHero#3]
Hey

It looks like on VS2019 this bit creates an infinite recursion and the game crashes at launch:
https://github.com/arc80/FlapHero/blob/c42edcc06c545bef7a9219f0727a4a46b883c370/src/flapGame/flapGame/Assets.cpp#L145-L147

because the second version of find is called (and then calls itself), while `forSkel` is actually already an ArrayView:
```c++
template <typename T, typename Callback, std::enable_if_t<IsCallable<Callback, T>, int> = 0>
PLY_INLINE s32 find(ArrayView<const T> arr, const Callback& callback) {
    for (u32 i = 0; i < arr.numItems; i++) {
        if (callback(arr[i]))
            return i;
    }
    return -1;
}

template <typename Arr, typename Arg, typename = details::ArrayViewType<Arr>>
PLY_INLINE s32 find(const Arr& arr, const Arg& arg) {
    return find(arr.view(), arg);
}
```

It's not clear to me why the overload taking an ArrayView isn't selected here 😞 

Edit: it looks like it has to do with T not being const, so ArrayView<const T> doesn't match here.

**Comment by preshing** [comment]
Thanks for reporting this. It's a bug caused by arc80/plywood@91c71de.

The overload taking an `ArrayView` isn't selected here because the compiler can't deduce any `T` in `ArrayView<const T>` that would match `ArrayView<Bone>`, since `Bone` is non-const. The compiler doesn't look at user-defined conversions during template argument deduction.

My first thought is to use a cast to `ArrayView` of const items instead of calling `view()` here -- that would state more specifically what we want. Might involve changing the `ArrayViewType` template a little bit. I'll investigate.

**Comment by jlaumon** [comment]
Thanks!
